### ISSUE TITLE
Formatting + localization for entry listing table view

### ISSUE THREAD

**Issue by siebird** [studioespresso/craft-date-range#10]
This has been a great field for creating an events section for my client. An events plugin would be overkill in this case. 

To help with them managing the events, I am showing the field in the entry listings table view. However, the formatting is less than ideal at this point. 

Ideally, having an option to show/hide the end date and localize the date formatting would be great. Maybe a field setting could accomplish this where you could enter format wanted or adopt the formatting from the user preferences.

[Screenshot here](https://d.pr/i/wn1Isx)

**Comment by janhenckens** [comment]
Formatting based on the users locale/preferences sounds like a good idea, I'll have a look if that's possible. 
Possibly related to [#9](https://github.com/studioespresso/craft-date-range/issues/9)

**Comment by janhenckens** [comment]
Just released an update that includes this. The formatting is now based on the user's locale, just like it is for Craft's date fields.

**Comment by siebird** [comment]
Awesome, work. Thanks for the quick turn around!

**Comment by janhenckens** [comment]
My pleasure! If you'd like to see anything else added to the plugin, you can always get in touch.
