### ISSUE TITLE
FR: Hide end date when it is the same as start date

### ISSUE THREAD

**Issue by carolineboeykens** [studioespresso/craft-date-range#15]
If your end date is the same as the start date we don't want to show it. But if the end time is different, we would like to show this. It would be nice if this is possible with your .formatted() function.

![Screen Shot 2020-02-27 at 09 08 42](https://user-images.githubusercontent.com/42932673/75424453-edc34d80-5940-11ea-83a2-db152926016e.png)

The output for this example would be: 07/04/2020 14:30 tot 17:00

**Comment by janhenckens** [comment]
Fixed in latest release, with some extra docs [here](https://github.com/studioespresso/craft-date-range#getformatted)
