### ISSUE TITLE
Error when using isOnGoing

### ISSUE THREAD

**Issue by martinsmith** [studioespresso/craft-date-range#2]
Hello, I get the following error when using isOnGoing? Too few arguments to function studioespresso\daterange\fields\data\DateRangeData::getIsOngoing(), 0 passed in /vendor/yiisoft/yii2/base/BaseObject.php on line 136 and exactly 2 expected

**Comment by janhenckens** [comment]
Hey Martin

Could you share the settings you're using for the field in question and the full stack trace of the error? Thanks!

**Comment by janhenckens** [comment]
Hey Martin

I released a fix for this yesterday, can you give it another try?
