### ISSUE TITLE
formatted is showing start and end date even if they are the same

### ISSUE THREAD

**Issue by carolineboeykens** [studioespresso/craft-date-range#21]
Example:
![Screen Shot 2020-11-02 at 13 31 07](https://user-images.githubusercontent.com/42932673/97868318-c0207680-1d0f-11eb-9440-978d0cee6bb8.png)

If the start date and the end date are the same it should only show the date once and the different hours.
Is that possible?

**Comment by janhenckens** [comment]
Fixed in 2.1.2!
