### ISSUE TITLE
Formatting date

### ISSUE THREAD

**Issue by carolineboeykens** [studioespresso/craft-date-range#22]
I'm having some issues with the format function:

If I try this:
`<div class="px-1">{{ entry.eventDate.formatted("F d, Y", "-"|t) }}</div>`
this happens:
<img width="318" alt="Screen Shot 2021-02-26 at 14 41 35" src="https://user-images.githubusercontent.com/42932673/111791980-13145800-88c4-11eb-9c52-1f6951be2fec.png">

If I try this:
`<div class="px-1">{{ entry.eventDate.formatted({ date: 'F d, Y', time: ''}, '-'|t) }}</div>`
this happens: 
<img width="228" alt="Screen Shot 2021-02-26 at 14 42 33" src="https://user-images.githubusercontent.com/42932673/111792057-21fb0a80-88c4-11eb-9022-2f8ddd6e5dd8.png">

Am I doing something wrong?

**Comment by janhenckens** [comment]
Fixed in todays update!
