### ISSUE TITLE
isFuture(), isPast(), isOngoing() Not Functional for MariaDB

### ISSUE THREAD

**Issue by JonGoldmanPlaybill** [studioespresso/craft-date-range#24]
Note that Nitro 2 on new Macs with Apple Silicon cannot install MySQL and use MariaDB (or PostGreSQL).  While I know the docs say that it is only MySQL compatible, this would be a request to make it usable in the MariaDB Environment.

**Comment by janhenckens** [comment]
Hey! Good idea. My previous mac couldn't really run Nitro but I switched to newer model so I'll have another look it.

**Comment by carolineboeykens** [comment]
Hi @janhenckens ,
I'm also having trouble with this issue. Could you look in to it?

**Comment by janhenckens** [comment]
Hey @JonGoldmanPlaybill @carolineboeykens, this should be fixed in 2.3.0.
Since MySQL 5.6 has been end of life since Februari 2021, I decided to remove the version check. Also included in this release is PostgreSQL support.
