### ISSUE TITLE
Craft 4 issues

### ISSUE THREAD

**Issue by cloudgrayau** [studioespresso/craft-date-range#32]
Hello,

This plugin is not working with Craft 4.0.4.

PHP Compile Error – [yii\base\ErrorException](http://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
Declaration of studioespresso\daterange\fields\DateRangeField::normalizeValue($value, ?craft\base\ElementInterface $element = null) must be compatible with craft\base\Field::normalizeValue(mixed $value, ?craft\base\ElementInterface $element = null): mixed

PHP Compile Error – [yii\base\ErrorException](http://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
Declaration of studioespresso\daterange\fields\DateRangeField::serializeValue($value, ?craft\base\ElementInterface $element = null) must be compatible with craft\base\Field::serializeValue(mixed $value, ?craft\base\ElementInterface $element = null): mixed

PHP Compile Error – [yii\base\ErrorException](http://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
Declaration of studioespresso\daterange\fields\DateRangeField::getContentGqlType() must be compatible with craft\base\Field::getContentGqlType(): GraphQL\Type\Definition\Type|array

Thanks,

**Comment by piotrpog** [comment]
Same issue here, error shows up when i open "new field" page in control panel.

**Comment by janhenckens** [comment]
Hey @cloudgrayau @piotrpog, sorry about that, I forgot to push a tag for the stable Craft 4 release. Added some extra GraphQL fixes too, can you try with 3.0.1?

Thanks!
