### ISSUE TITLE
beta 1 is crashing craft 4

### ISSUE THREAD

**Issue by ballmannweber** [studioespresso/craft-date-range#33]
I tried to update a craft 3 site to craft 4 with the beta 1 version which results in this error:

`Copy Stacktrace Search Stackoverflow Search Google Error
PHP Compile Error – [yii\base\ErrorException](http://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)

Declaration of studioespresso\daterange\fields\DateRangeField::normalizeValue($value, ?craft\base\ElementInterface $element = null) must be compatible with craft\base\Field::normalizeValue(mixed $value, ?craft\base\ElementInterface $element = null): mixed`

**Comment by ballmannweber** [comment]
no replies?

**Comment by janhenckens** [comment]
Can you check that you're on the latest version of the plugin? 3.0.1 fixed this and was released June 19th.
