### ISSUE TITLE
Data disappears

### ISSUE THREAD

**Issue by martinsmith** [studioespresso/craft-date-range#4]
Hello, i'm using the field inside SuperTable, whenever I save the entry the values I added are removed from the Date Range field?  When I go back in the field is blank again?

**Comment by janhenckens** [comment]
Hey Martin, that's not supposed to happen. I'll test it in a supertable field as well and see if I can reproduce (and fix) it.

**Comment by martinsmith** [comment]
Thank you :)

**Comment by martinsmith** [comment]
I don't know if this helps?

![image](https://user-images.githubusercontent.com/5725864/69971462-d7f7e500-1517-11ea-9089-95a9f1b1c395.png)

**Comment by janhenckens** [comment]
It does, thanks!

**Comment by martinsmith** [comment]
Hi,  I noticed you published an update so I updated.  Indeed the fields now retain their data BUT if one field is left blank then all fields are stripped as before.   Scenario: A single workshop runs on a single night so there is no need for the 'end date', but it does have an 'end time'.  If I leave 'End Date' blank all fields are emptied on save.

**Comment by janhenckens** [comment]
Yes, that is something that I'm looking at. For the other plugins functions (future, past, ongoing) to work, I need both dates.

My current idea is that if the end date is left empty, I'll just use the start value and add it there as well. Would that work for you?

**Comment by martinsmith** [comment]
That could work.  Would that work with conditionals?  {% if fieldName.end %} Show end date {% endif %}

**Comment by janhenckens** [comment]
Yep, you can do things like `{% if fieldName.start|date('d/m/Y') == fieldName.end|date('d/m/Y') %}` etc...

I'll try to add this tonight or tomorrow :)

**Comment by martinsmith** [comment]
Thank you!

**Comment by janhenckens** [comment]
Hey Martin, sorry for the slight delay, this just got released!
