### ISSUE TITLE
Add label localization

### ISSUE THREAD

**Issue by ockam** [studioespresso/craft-date-range#6]
Please use the t function for control panel display in DateRange_input.twig, so we can add translations for:
- Start date
- Start time
- End date
- End time

**Comment by janhenckens** [comment]
Ooops, my bad @ockam, will add those right away!
If you want to, you can send me the translations and I'll add them in the plugin, so you don't have to add them to each site.

**Comment by ockam** [comment]
Here’s the french locale, if you wan to add it, but I can deal with it locally. Your call.

```
return [
  'Start date' => 'Date de début',
  'Start time' => 'Heure de début',
  'End date' => 'Date de fin',
  'End time' => 'Heure de fin',
];
```
Thanks for the quick response!

**Comment by janhenckens** [comment]
Thanks for those!
Are the sites you're building in specific French locale or the general one?

**Comment by ockam** [comment]
I’m actually on `fr-CA`, but I think those are generic enough for just `fr`

**Comment by janhenckens** [comment]
Added these in 1.2.2, which I just released.
