### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by ockam** [studioespresso/craft-date-range#7]
Please, if possible, add some documentation on using the query behavior in a query.

Following your suggestion on Discord, i have successfully been able to make this query work:

`craft.entries().section('publications').isOnGoing('fieldHandle').all()`

But now, I need to check 2 date range fields with a orWhere query. Please advise.

**Comment by janhenckens** [comment]
Done! https://github.com/studioespresso/craft-date-range#element-querries

**Comment by ockam** [comment]
queries only takes one r

**Comment by janhenckens** [comment]
Oops, fixed :)
