### ISSUE TITLE
24 hour format

### ISSUE THREAD

**Issue by magnusskogen** [studioespresso/craft-date-range#9]
Great plugin! Any chance that we can get a setting to choose between 24 hours and AM/PM?

**Comment by janhenckens** [comment]
Hey Magnuss, not sur if that's possible. The plugin is using Craft's time field so if it's possible there it should be possible in the plugin. I'll have a look!

**Comment by janhenckens** [comment]
Hey @magnusskogen 
I did a bit of research into this and the date field is following the same settings as Craft's core date/time fields like post date & expiry date. Just like those, the formatting of the time depends on the locale that is set for the current user. 

I want to stick as close to Craft as I can on this, the keep the CP experience seamless for CP users.

Feel free to comment if you have any further thoughts and/or suggestions!
